<?php
/**
 * Created by PhpStorm.
 * User: bratucornel
 * Date: 2019-02-22
 * Time: 10:25
 */

namespace Retargeting;


use PHPUnit\Framework\TestCase;

/**
 * @property Product product
 */
class ApiCustomersTest extends TestCase
{

    protected $customer = [
        'firstName' => 'John',
        'lastName' => 'Doe',
        'email' => 'john.doe@example.com',
        'phone' => '0770000000',
        'status' => true
    ];

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    //@TODO: write tests
}
