<?php
/**
 * Created by PhpStorm.
 * User: serbanmunteanu
 * Date: 2019-02-22
 * Time: 14:29
 */

namespace Retargeting;
use PHPUnit\Framework\TestCase;

/***
 * Class BrandTest
 * @package Retargeting
 * @property Brand brand
 */

class BrandTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->brand = new Brand();
    }

    public function testPrepareBrandInformation()
    {

    }

    public function testGetName()
    {

    }

    public function testGetId()
    {

    }

    public function testSetName()
    {

    }

    public function testSetId()
    {

    }
}
