<?php
/**
 * Created by PhpStorm.
 * User: serbanmunteanu
 * Date: 2019-02-22
 * Time: 14:23
 */
namespace Retargeting;
use PHPUnit\Framework\TestCase;

/**
 * Class CategoryTest
 * @package Retargeting
 * @property Category category
 */
class CategoryTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->category = new Category();
    }

    public function testSetId()
    {

    }

    public function testGetId()
    {

    }
}
