<?php
/**
 * Created by PhpStorm.
 * User: serbanmunteanu
 * Date: 2019-02-22
 * Time: 17:45
 */

namespace Retargeting;
use PHPUnit\Framework\TestCase;

/**
 * Class CheckoutTest
 * @package Retargeting
 * @property Checkout checkout
 */
class CheckoutTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->checkout = new Checkout();
    }

    public function testPrepareCheckoutIdsArray()
    {

    }

    public function testSetIds()
    {

    }

    public function testGetIds()
    {

    }
}
