<?php
/**
 * Created by PhpStorm.
 * User: serbanmunteanu
 * Date: 2019-02-22
 * Time: 17:26
 */

namespace Retargeting;
use PHPUnit\Framework\TestCase;

/**
 * Class EmailTest
 * @package Retargeting
 * @property Email email
 */

class EmailTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->email= new Email();
    }

    public function testSetEmail()
    {

    }

    public function testGetCity()
    {

    }

    public function testGetPhone()
    {

    }

    public function testGetSex()
    {

    }

    public function testPrepareEmailInfo()
    {

    }

    public function testGetEmail()
    {

    }

    public function testSetBirthday()
    {

    }

    public function testSetName()
    {

    }

    public function testSetPhone()
    {

    }

    public function testSetCity()
    {

    }

    public function testSetSex()
    {

    }

    public function testGetBirthday()
    {

    }

    public function testGetName()
    {

    }
}
