<?php
/**
 * Created by PhpStorm.
 * User: andreicotaga
 * Date: 2019-03-15
 * Time: 17:27
 */

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use Retargeting\Email;

/**
 * @property Email email
 */
class EmailTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->email = new Email();
    }

    public function test_if_email_is_not_empty()
    {
        $this->email->setEmail('test@google.com');

        $this->assertNotEmpty($this->email->getEmail());
    }
}