<?php
/**
 * Created by PhpStorm.
 * User: andreicotaga
 * Date: 2019-03-15
 * Time: 17:46
 */

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use Retargeting\OrderProducts;

/**
 * Class OrderProductsTest
 * @package Tests\Unit
 * @property OrderProducts orderProducts
 */
class OrderProductsTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->orderProducts = new OrderProducts();
    }

    public function testIfOrderProductsHasId()
    {
        $this->orderProducts->setId(111);
        $this->assertNotNull($this->orderProducts->getId());
    }

    public function testIfOrderProductsHasQuantity()
    {
        $this->orderProducts->setQuantity(1);
        $this->assertNotNull($this->orderProducts->getQuantity());
    }
}