<?php
/**
 * Created by PhpStorm.
 * User: andreicotaga
 * Date: 2019-03-15
 * Time: 17:23
 */

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use Retargeting\Order;

/**
 * @property Order order
 */
class OrderTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->order = new Order();
    }

    public function test_if_order_has_no()
    {
        $this->order->setOrderNo(28);

        $this->assertNotNull($this->order->getOrderNo());
    }
}