<?php
/**
 * Created by PhpStorm.
 * User: bratucornel
 * Date: 2019-02-22
 * Time: 10:25
 */

namespace Retargeting;


use PHPUnit\Framework\TestCase;

/**
 * @property Product product
 */
class ProductTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = new Product();
        $this->product->setUrl('http://google.ro');
    }

    public function test_if_product_has_id()
    {
        $this->product->setId(123);
        $this->assertNotNull($this->product->getId());
    }

    public function test_if_product_has_name()
    {

        $this->product->setName('Fooo');
        $this->assertNotNull($this->product->getName());
    }

    public function test_if_product_url_is_set(){
        $this->assertEquals($this->product->getUrl(), 'http://google.ro');
    }

}
